# This is a basic workflow to help you get started with Actions

name: Test

on: [push]

permissions:
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Jest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    # Steps represent a sequence of tasks that will be executed as part of the job
   
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with: 
         node-version: ${{ matrix.node-version }}
         cache: 'npm'
    - run: npm ci
    - run: npm test
